FROM golang:alpine AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o server ./main.go

FROM scratch
WORKDIR /app/
COPY --from=builder /app/server .
CMD ["./server"]


